# fly.toml app configuration file generated for proxy-whoant-1 on 2023-07-27T16:30:13+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "proxy-whoant-1"
primary_region = "nrt"

[http_service]
  internal_port = 8081
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/ping"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[services.ports]]
    port = 1234
  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200
